accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"

urlpatterns = [
    path('register', register_user, name='register'),
    path('login', login_user, name='login'),
    path('logout', logout_user, name='logout'),
]

core/urls.py
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = "core"

urlpatterns = [
    path('', home, name='home'),
    path('artists', ArtistListView.as_view(), name='artists'),
    path('artists/<slug:slug>', ArtistDetailView.as_view(), name='artist-details'),
    path('genres', GenreListView.as_view(), name='genres'),
    path('genres/<int:pk>', SongsByGenreListView.as_view(), name='songs-by-genre'),
    path('songs/', include([
        path('make-favorite', favoriteunfavorite, name='song-favorite'),
        path('upload', SongUploadView.as_view(), name='upload'),
        path('<slug:audio_id>', SongDetailsView.as_view(), name='upload-details'),
    ])),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),

    # API Urls
    path('v1/api/', include([
        path('', include('core.api.urls')),
        path('accounts/', include('accounts.api.urls')),
    ])),
]

templates/includes/dropdown.html
<li class="dropleft">
    <a href="javascript:void(0);" class="btn btn-icon-only p-0 w-auto h-auto" data-toggle="dropdown"
       aria-haspopup="true" aria-expanded="false">
        <i class="la la-ellipsis-h"></i>
    </a>
    <ul class="dropdown-menu">
        <li class="dropdown-item">
            <a href="javascript:void(0);" class="dropdown-link favorite">
                <i class="la la-heart-o"></i> <span>Favorite</span>
            </a>
        </li>
        <li class="dropdown-item">
            <a href="javascript:void(0);" class="dropdown-link">
                <i class="la la-plus"></i> <span>Add to Playlist</span>
            </a>
        </li>
        <li class="dropdown-item">
            <a href="javascript:void(0);" class="dropdown-link">
                <i class="la la-download"></i> <span>Download</span>
            </a>
        </li>
        <li class="dropdown-item">
            <a href="javascript:void(0);" class="dropdown-link">
                <i class="la la-share-alt"></i> <span>Share</span>
            </a>
        </li>
        <li class="dropdown-item">
            {% if song %}
                <a href="{% url 'core:upload-details' song.audio_id %}" class="dropdown-link">
                    <i class="la la-info-circle"></i> <span>Song Info</span>
                </a>
            {% endif %}
        </li>
    </ul>
</li>

templates/includes/footer.html
<div id="audioPlayer" class="player-primary">
    <div id="progress-container">
        <input type="range" class="amplitude-song-slider">
        <progress id="song-played-progress" class="audio-progress audio-progress--played amplitude-song-played-progress"></progress>
        <progress id="song-buffered-progress" class="audio-progress audio-progress--buffered amplitude-buffered-progress"></progress>
    </div>
    <div class="audio">
        <div class="song-image">
            <img data-amplitude-song-info="cover_art_url" src="" alt="">
        </div>
        <div class="song-info pl-3">
            <span class="song-name d-inline-block text-truncate" data-amplitude-song-info="name"></span>
            <span class="song-artists d-block text-muted" data-amplitude-song-info="artist"></span>
        </div>
    </div>
    <div class="audio-controls">
        <div class="audio-controls--left d-flex mr-auto">
            <button class="btn btn-icon-only amplitude-repeat">
                <i class="ion-md-sync"></i>
            </button>
        </div>
        <div class="audio-controls--main d-flex">
            <button class="btn btn-icon-only amplitude-prev">
                <i class="ion-md-skip-backward"></i>
            </button>
            <button class="btn btn-air btn-pill btn-default btn-icon-only amplitude-play-pause">
                <i class="ion-md-play"></i> <i class="ion-md-pause"></i>
            </button>
            <button class="btn btn-icon-only amplitude-next">
                <i class="ion-md-skip-forward"></i>
            </button>
        </div>
        <div class="audio-controls--right d-flex ml-auto">
            <button class="btn btn-icon-only amplitude-shuffle amplitude-shuffle-off">
                <i class="ion-md-shuffle"></i>
            </button>
        </div>
    </div>
    <div class="audio-info d-flex align-items-center pr-4">
        <span class="mr-4">
            <span class="amplitude-current-minutes"></span>:<span class="amplitude-current-seconds"></span> /
            <span class="amplitude-duration-minutes"></span>:<span class="amplitude-duration-seconds"></span>
        </span>
        <div class="audio-volume dropdown">
            <button class="btn btn-icon-only" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="ion-md-volume-low"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right volume-dropdown-menu">
                <input type="range" class="amplitude-volume-slider">
            </div>
        </div>
        <div class="dropleft">
            <button class="btn btn-icon-only" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="la la-ellipsis-v"></i></button>
            <ul class="dropdown-menu">
                <li class="dropdown-item">
                    <a href="javascript:void(0);" class="dropdown-link">
                        <i class="la la-heart-o"></i>
                        <span>Favorite</span>
                    </a>
                </li>
                <li class="dropdown-item">
                    <a href="javascript:void(0);" class="dropdown-link">
                        <i class="la la-plus"></i> <span>Add to Playlist</span>
                    </a>
                </li>
                <li class="dropdown-item">
                    <a href="javascript:void(0);" class="dropdown-link">
                        <i class="la la-download"></i> <span>Download</span>
                    </a>
                </li>
                <li class="dropdown-item">
                    <a href="javascript:void(0);" class="dropdown-link">
                        <i class="la la-share-alt"></i> <span>Share</span>
                    </a>
                </li>
                <li class="dropdown-item">
                    <a href="#" class="dropdown-link">
                        <i class="la la-info-circle"></i> <span>Song Info</span>
                    </a>
                </li>
            </ul>
        </div>
        <button class="btn btn-icon-only" id="playList"><i class="ion-md-musical-note"></i></button>
    </div>
</div>

<footer id="footer" class="bg-img">
    <div class="footer-content">
        <div class="platform-btn-inline">
            <a href="#" class="btn btn-dark btn-air platform-btn">
                <i class="ion-logo-android"></i>
                <div class="platform-btn-info">
                    <span class="platform-desc">Available on</span>
                    <span class="platform-name">Android</span>
                </div>
            </a>
            <a href="#" class="btn btn-danger btn-air platform-btn">
                <i class="ion-logo-apple"></i>
                <div class="platform-btn-info">
                    <span class="platform-desc">Available on</span>
                    <span class="platform-name">App Store</span>
                </div>
            </a>
        </div>
    </div>
</footer>

<div class="modal fade" id="shareModal" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h4 class="modal-title">Share</h4>
                <button type="button" class="close" data-dismiss="modal">×</button>
            </div>

            <div class="modal-body text-center">
                <div class="mb-2">
                    <img src="https://www.qrcoder.co.uk/api/v1/?size=5&amp;text=music-app">
                </div>
                <a href="#" onclick="MyWindow=window.open('https://www.facebook.com/dialog/share?app_id=&amp;display=popup&amp;href=music-app','Facebook share','width=600,height=300'); return false;" class="btn btn-primary btn-sm waves-effect waves-light">
                    <i class="fa fa-facebook"></i>
                </a>
                <a href="#" onclick="MyWindow=window.open('https://twitter.com/share?url=music-app','Twitt this','width=600,height=300'); return false;" class="btn btn-info btn-sm waves-effect waves-light">
                    <i class="fa fa-twitter"></i>
                </a>
                <a href="#" onclick="MyWindow=window.open('https://www.linkedin.com/shareArticle?mini=true&url=music-app&title=Listen-App','Twitt this','width=600,height=300'); return false;" class="btn btn-success btn-sm waves-effect waves-light">
                    <i class="fa fa-linkedin"></i>
                </a>
            </div>

            <div class="modal-footer">
                <button class="btn btn-danger btn-sm waves-effect waves-light" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

templates/includes/javascripts.html
{% load static %}
<script src="{% static 'js/vendors.bundle.js' %}"></script>
<script src="{% static 'js/scripts.bundle.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js" type="text/javascript"
        charset="utf-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tag-it/2.0/js/tag-it.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
<script src="{% static 'js/custom.js' %}"></script>
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
{% block scripts %}{% endblock %}

templates/includes/nav.html
{% load static %}
<header id="header" class="bg-primary">
    <div class="d-flex align-items-center">
        <button type="button" class="btn toggle-menu mr-3" id="openSidebar">
            <span></span>
            <span></span>
            <span></span>
        </button>
        <form action="#" id="searchForm">
            <button type="button" class="btn ion-ios-search"></button>
            <input type="text" placeholder="Search..." class="form-control" id="search" data-search-url="#">
            <div class="search-card" data-scrollable="true">
                <div class="mb-3">
                    <div class="d-flex">
                        <span class="text-uppercase mr-auto font-weight-bold text-dark">Track</span>
                        <a href="#">View All</a>
                    </div>
                    <hr>
                    <div class="row" id="search-track">

                    </div>
                </div>
            </div>
        </form>
        <ul class="header-options d-flex align-items-center">
            {% if request.user.is_authenticated %}
                <li>
                    <a href="{% url 'core:upload' %}" class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24">
                            <path fill="currentColor"
                                  d="M16,9V7H12V12.5C11.58,12.19 11.07,12 10.5,12A2.5,2.5 0 0,0 8,14.5A2.5,2.5 0 0,0 10.5,17A2.5,2.5 0 0,0 13,14.5V9H16M12,2A10,10 0 0,1 22,12A10,10 0 0,1 12,22A10,10 0 0,1 2,12A10,10 0 0,1 12,2Z">
                            </path>
                        </svg>
                        Upload
                    </a>
                </li>
                <li class="dropdown fade-in">
                    <a href="javascript:void(0);" class="d-flex align-items-center py-2"
                       role="button" id="userMenu" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <div class="avatar avatar-sm avatar-circle">
                            <img src="{% static 'images/users/avatar.jpg' %}" alt="user">
                        </div>
                        <span class="pl-2">Hello {{ request.user.name }}</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                        <a class="dropdown-item" href="#">
                            <i class="ion-md-contact"></i>
                            <span>Profile</span></a>
                        <a class="dropdown-item" href="#">
                            <i class="ion-md-radio-button-off"></i>
                            <span>Your Plan</span>
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="ion-md-settings"></i>
                            <span>Settings</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <div class="px-4 py-2">
                            <a href="{% url 'accounts:logout' %}" class="btn btn-sm btn-air btn-pill btn-danger">Logout</a>
                        </div>
                    </div>
                </li>
            {% else %}
                <li>
                    <a href="javascript:void(0);" data-toggle="modal" data-target="#login">
                        <span>Login</span>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0);" data-toggle="modal" data-target="#register">
                        <span>Register</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
</header>

templates/includes/sidebar.html
{% load static %}
<aside id="sidebar" class="sidebar-primary">
    <div class="sidebar-header d-flex align-items-center">
        <a href="/" class="brand">
            <img src="{% static 'images/logos/logo.png' %}" alt="listen-app">
        </a>
        <button type="button" class="btn p-0 ml-auto" id="hideSidebar">
            <i class="ion-md-arrow-back h3"></i>
        </button>
        <button type="button" class="btn toggle-menu" id="toggleSidebar">
            <span></span>
            <span></span>
            <span></span>
        </button>
    </div>
    <nav class="navbar">
        <ul class="navbar-nav" data-scrollable="true">
            <li class="nav-item nav-header">Browse Music</li>
            <li class="nav-item">
                <a href="/" class="nav-link">
                    <i class="la la-home"></i>
                    <span>Home</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'core:genres' %}" class="nav-link">
                    <i class="la la-diamond"></i>
                    <span>Genres</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="la la-music"></i>
                    <span>Free Music</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'core:artists' %}" class="nav-link">
                    <i class="la la-microphone"></i>
                    <span>Artists</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="la la-bullseye"></i>
                    <span>Stations</span>
                </a>
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item nav-header">Your Music</li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="la la-heart-o"></i>
                        <span>Favorites</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="la la-history"></i>
                        <span>History</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
</aside>

templates/includes/stylesheets.html
{% load static %}
<link href="{% static 'css/vendors.bundle.css' %}" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Roboto+Slab:100,300,400,700" rel="stylesheet">
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
<link rel="stylesheet" type="text/css"
      href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/tag-it/2.0/css/jquery.tagit.min.css" rel="stylesheet"
      type="text/css">
<link href="{% static 'css/styles.bundle.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'css/toastr.min.css' %}">